/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardContractsIndexRouteImport } from './routes/dashboard/contracts/index'
import { Route as DashboardContractsContractIdRouteRouteImport } from './routes/dashboard/contracts/$contractId/route'
import { Route as DashboardContractsNewRouteImport } from './routes/dashboard/contracts/new'
import { Route as DashboardEmployeesIndexRouteImport } from './routes/dashboard/employees/index'
import { Route as DashboardEmployeesEmployeeIdRouteImport } from './routes/dashboard/employees/$employeeId'
import { Route as DashboardEmployeesNewRouteImport } from './routes/dashboard/employees/new'
import { Route as DashboardInvoicesIndexRouteImport } from './routes/dashboard/invoices/index'
import { Route as DashboardInvoicesInvoiceIdRouteImport } from './routes/dashboard/invoices/$invoiceId'
import { Route as DashboardInvoicesNewRouteImport } from './routes/dashboard/invoices/new'
import { Route as DashboardPayrollIndexRouteImport } from './routes/dashboard/payroll/index'
import { Route as DashboardPayrollPayrollIdRouteImport } from './routes/dashboard/payroll/$payrollId'
import { Route as DashboardPayrollNewRouteImport } from './routes/dashboard/payroll/new'
import { Route as DashboardSettingsOrganizationRouteImport } from './routes/dashboard/settings/organization'
import { Route as DashboardSettingsTaxRouteImport } from './routes/dashboard/settings/tax'
import { Route as DashboardContractsContractIdIndexRouteImport } from './routes/dashboard/contracts/$contractId/index'
import { Route as DashboardContractsContractIdActivityRouteImport } from './routes/dashboard/contracts/$contractId/activity'
import { Route as DashboardContractsContractIdDeadlinesRouteImport } from './routes/dashboard/contracts/$contractId/deadlines'
import { Route as DashboardContractsContractIdDocumentsRouteImport } from './routes/dashboard/contracts/$contractId/documents'
import { Route as DashboardContractsContractIdEmployeesRouteImport } from './routes/dashboard/contracts/$contractId/employees'
import { Route as DashboardContractsContractIdInvoicesRouteImport } from './routes/dashboard/contracts/$contractId/invoices'
import { Route as DashboardContractsContractIdPayrollRouteImport } from './routes/dashboard/contracts/$contractId/payroll'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContractsIndexRoute = DashboardContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContractsContractIdRouteRoute =
  DashboardContractsContractIdRouteRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardContractsNewRoute = DashboardContractsNewRouteImport.update({
  id: '/contracts/new',
  path: '/contracts/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmployeesIndexRoute = DashboardEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmployeesEmployeeIdRoute =
  DashboardEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmployeesNewRoute = DashboardEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvoicesIndexRoute = DashboardInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvoicesInvoiceIdRoute =
  DashboardInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInvoicesNewRoute = DashboardInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPayrollIndexRoute = DashboardPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPayrollPayrollIdRoute =
  DashboardPayrollPayrollIdRouteImport.update({
    id: '/payroll/$payrollId',
    path: '/payroll/$payrollId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPayrollNewRoute = DashboardPayrollNewRouteImport.update({
  id: '/payroll/new',
  path: '/payroll/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsOrganizationRoute =
  DashboardSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsTaxRoute = DashboardSettingsTaxRouteImport.update({
  id: '/settings/tax',
  path: '/settings/tax',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContractsContractIdIndexRoute =
  DashboardContractsContractIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)
const DashboardContractsContractIdActivityRoute =
  DashboardContractsContractIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)
const DashboardContractsContractIdDeadlinesRoute =
  DashboardContractsContractIdDeadlinesRouteImport.update({
    id: '/deadlines',
    path: '/deadlines',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)
const DashboardContractsContractIdDocumentsRoute =
  DashboardContractsContractIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)
const DashboardContractsContractIdEmployeesRoute =
  DashboardContractsContractIdEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)
const DashboardContractsContractIdInvoicesRoute =
  DashboardContractsContractIdInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)
const DashboardContractsContractIdPayrollRoute =
  DashboardContractsContractIdPayrollRouteImport.update({
    id: '/payroll',
    path: '/payroll',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/contracts/$contractId': typeof DashboardContractsContractIdRouteRouteWithChildren
  '/dashboard/contracts/new': typeof DashboardContractsNewRoute
  '/dashboard/employees/$employeeId': typeof DashboardEmployeesEmployeeIdRoute
  '/dashboard/employees/new': typeof DashboardEmployeesNewRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/invoices/new': typeof DashboardInvoicesNewRoute
  '/dashboard/payroll/$payrollId': typeof DashboardPayrollPayrollIdRoute
  '/dashboard/payroll/new': typeof DashboardPayrollNewRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/tax': typeof DashboardSettingsTaxRoute
  '/dashboard/contracts/': typeof DashboardContractsIndexRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/dashboard/payroll/': typeof DashboardPayrollIndexRoute
  '/dashboard/contracts/$contractId/activity': typeof DashboardContractsContractIdActivityRoute
  '/dashboard/contracts/$contractId/deadlines': typeof DashboardContractsContractIdDeadlinesRoute
  '/dashboard/contracts/$contractId/documents': typeof DashboardContractsContractIdDocumentsRoute
  '/dashboard/contracts/$contractId/employees': typeof DashboardContractsContractIdEmployeesRoute
  '/dashboard/contracts/$contractId/invoices': typeof DashboardContractsContractIdInvoicesRoute
  '/dashboard/contracts/$contractId/payroll': typeof DashboardContractsContractIdPayrollRoute
  '/dashboard/contracts/$contractId/': typeof DashboardContractsContractIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/contracts/new': typeof DashboardContractsNewRoute
  '/dashboard/employees/$employeeId': typeof DashboardEmployeesEmployeeIdRoute
  '/dashboard/employees/new': typeof DashboardEmployeesNewRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/invoices/new': typeof DashboardInvoicesNewRoute
  '/dashboard/payroll/$payrollId': typeof DashboardPayrollPayrollIdRoute
  '/dashboard/payroll/new': typeof DashboardPayrollNewRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/tax': typeof DashboardSettingsTaxRoute
  '/dashboard/contracts': typeof DashboardContractsIndexRoute
  '/dashboard/employees': typeof DashboardEmployeesIndexRoute
  '/dashboard/invoices': typeof DashboardInvoicesIndexRoute
  '/dashboard/payroll': typeof DashboardPayrollIndexRoute
  '/dashboard/contracts/$contractId/activity': typeof DashboardContractsContractIdActivityRoute
  '/dashboard/contracts/$contractId/deadlines': typeof DashboardContractsContractIdDeadlinesRoute
  '/dashboard/contracts/$contractId/documents': typeof DashboardContractsContractIdDocumentsRoute
  '/dashboard/contracts/$contractId/employees': typeof DashboardContractsContractIdEmployeesRoute
  '/dashboard/contracts/$contractId/invoices': typeof DashboardContractsContractIdInvoicesRoute
  '/dashboard/contracts/$contractId/payroll': typeof DashboardContractsContractIdPayrollRoute
  '/dashboard/contracts/$contractId': typeof DashboardContractsContractIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/contracts/$contractId': typeof DashboardContractsContractIdRouteRouteWithChildren
  '/dashboard/contracts/new': typeof DashboardContractsNewRoute
  '/dashboard/employees/$employeeId': typeof DashboardEmployeesEmployeeIdRoute
  '/dashboard/employees/new': typeof DashboardEmployeesNewRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/invoices/new': typeof DashboardInvoicesNewRoute
  '/dashboard/payroll/$payrollId': typeof DashboardPayrollPayrollIdRoute
  '/dashboard/payroll/new': typeof DashboardPayrollNewRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/tax': typeof DashboardSettingsTaxRoute
  '/dashboard/contracts/': typeof DashboardContractsIndexRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/dashboard/payroll/': typeof DashboardPayrollIndexRoute
  '/dashboard/contracts/$contractId/activity': typeof DashboardContractsContractIdActivityRoute
  '/dashboard/contracts/$contractId/deadlines': typeof DashboardContractsContractIdDeadlinesRoute
  '/dashboard/contracts/$contractId/documents': typeof DashboardContractsContractIdDocumentsRoute
  '/dashboard/contracts/$contractId/employees': typeof DashboardContractsContractIdEmployeesRoute
  '/dashboard/contracts/$contractId/invoices': typeof DashboardContractsContractIdInvoicesRoute
  '/dashboard/contracts/$contractId/payroll': typeof DashboardContractsContractIdPayrollRoute
  '/dashboard/contracts/$contractId/': typeof DashboardContractsContractIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/welcome'
    | '/dashboard/'
    | '/dashboard/contracts/$contractId'
    | '/dashboard/contracts/new'
    | '/dashboard/employees/$employeeId'
    | '/dashboard/employees/new'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/invoices/new'
    | '/dashboard/payroll/$payrollId'
    | '/dashboard/payroll/new'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/tax'
    | '/dashboard/contracts/'
    | '/dashboard/employees/'
    | '/dashboard/invoices/'
    | '/dashboard/payroll/'
    | '/dashboard/contracts/$contractId/activity'
    | '/dashboard/contracts/$contractId/deadlines'
    | '/dashboard/contracts/$contractId/documents'
    | '/dashboard/contracts/$contractId/employees'
    | '/dashboard/contracts/$contractId/invoices'
    | '/dashboard/contracts/$contractId/payroll'
    | '/dashboard/contracts/$contractId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/dashboard'
    | '/dashboard/contracts/new'
    | '/dashboard/employees/$employeeId'
    | '/dashboard/employees/new'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/invoices/new'
    | '/dashboard/payroll/$payrollId'
    | '/dashboard/payroll/new'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/tax'
    | '/dashboard/contracts'
    | '/dashboard/employees'
    | '/dashboard/invoices'
    | '/dashboard/payroll'
    | '/dashboard/contracts/$contractId/activity'
    | '/dashboard/contracts/$contractId/deadlines'
    | '/dashboard/contracts/$contractId/documents'
    | '/dashboard/contracts/$contractId/employees'
    | '/dashboard/contracts/$contractId/invoices'
    | '/dashboard/contracts/$contractId/payroll'
    | '/dashboard/contracts/$contractId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/welcome'
    | '/dashboard/'
    | '/dashboard/contracts/$contractId'
    | '/dashboard/contracts/new'
    | '/dashboard/employees/$employeeId'
    | '/dashboard/employees/new'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/invoices/new'
    | '/dashboard/payroll/$payrollId'
    | '/dashboard/payroll/new'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/tax'
    | '/dashboard/contracts/'
    | '/dashboard/employees/'
    | '/dashboard/invoices/'
    | '/dashboard/payroll/'
    | '/dashboard/contracts/$contractId/activity'
    | '/dashboard/contracts/$contractId/deadlines'
    | '/dashboard/contracts/$contractId/documents'
    | '/dashboard/contracts/$contractId/employees'
    | '/dashboard/contracts/$contractId/invoices'
    | '/dashboard/contracts/$contractId/payroll'
    | '/dashboard/contracts/$contractId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contracts/': {
      id: '/dashboard/contracts/'
      path: '/contracts'
      fullPath: '/dashboard/contracts/'
      preLoaderRoute: typeof DashboardContractsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contracts/$contractId': {
      id: '/dashboard/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/dashboard/contracts/$contractId'
      preLoaderRoute: typeof DashboardContractsContractIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contracts/new': {
      id: '/dashboard/contracts/new'
      path: '/contracts/new'
      fullPath: '/dashboard/contracts/new'
      preLoaderRoute: typeof DashboardContractsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/employees/': {
      id: '/dashboard/employees/'
      path: '/employees'
      fullPath: '/dashboard/employees/'
      preLoaderRoute: typeof DashboardEmployeesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/employees/$employeeId': {
      id: '/dashboard/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/dashboard/employees/$employeeId'
      preLoaderRoute: typeof DashboardEmployeesEmployeeIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/employees/new': {
      id: '/dashboard/employees/new'
      path: '/employees/new'
      fullPath: '/dashboard/employees/new'
      preLoaderRoute: typeof DashboardEmployeesNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices/': {
      id: '/dashboard/invoices/'
      path: '/invoices'
      fullPath: '/dashboard/invoices/'
      preLoaderRoute: typeof DashboardInvoicesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices/$invoiceId': {
      id: '/dashboard/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/dashboard/invoices/$invoiceId'
      preLoaderRoute: typeof DashboardInvoicesInvoiceIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices/new': {
      id: '/dashboard/invoices/new'
      path: '/invoices/new'
      fullPath: '/dashboard/invoices/new'
      preLoaderRoute: typeof DashboardInvoicesNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/payroll/': {
      id: '/dashboard/payroll/'
      path: '/payroll'
      fullPath: '/dashboard/payroll/'
      preLoaderRoute: typeof DashboardPayrollIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/payroll/$payrollId': {
      id: '/dashboard/payroll/$payrollId'
      path: '/payroll/$payrollId'
      fullPath: '/dashboard/payroll/$payrollId'
      preLoaderRoute: typeof DashboardPayrollPayrollIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/payroll/new': {
      id: '/dashboard/payroll/new'
      path: '/payroll/new'
      fullPath: '/dashboard/payroll/new'
      preLoaderRoute: typeof DashboardPayrollNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/organization': {
      id: '/dashboard/settings/organization'
      path: '/settings/organization'
      fullPath: '/dashboard/settings/organization'
      preLoaderRoute: typeof DashboardSettingsOrganizationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/tax': {
      id: '/dashboard/settings/tax'
      path: '/settings/tax'
      fullPath: '/dashboard/settings/tax'
      preLoaderRoute: typeof DashboardSettingsTaxRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contracts/$contractId/': {
      id: '/dashboard/contracts/$contractId/'
      path: '/'
      fullPath: '/dashboard/contracts/$contractId/'
      preLoaderRoute: typeof DashboardContractsContractIdIndexRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
    '/dashboard/contracts/$contractId/activity': {
      id: '/dashboard/contracts/$contractId/activity'
      path: '/activity'
      fullPath: '/dashboard/contracts/$contractId/activity'
      preLoaderRoute: typeof DashboardContractsContractIdActivityRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
    '/dashboard/contracts/$contractId/deadlines': {
      id: '/dashboard/contracts/$contractId/deadlines'
      path: '/deadlines'
      fullPath: '/dashboard/contracts/$contractId/deadlines'
      preLoaderRoute: typeof DashboardContractsContractIdDeadlinesRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
    '/dashboard/contracts/$contractId/documents': {
      id: '/dashboard/contracts/$contractId/documents'
      path: '/documents'
      fullPath: '/dashboard/contracts/$contractId/documents'
      preLoaderRoute: typeof DashboardContractsContractIdDocumentsRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
    '/dashboard/contracts/$contractId/employees': {
      id: '/dashboard/contracts/$contractId/employees'
      path: '/employees'
      fullPath: '/dashboard/contracts/$contractId/employees'
      preLoaderRoute: typeof DashboardContractsContractIdEmployeesRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
    '/dashboard/contracts/$contractId/invoices': {
      id: '/dashboard/contracts/$contractId/invoices'
      path: '/invoices'
      fullPath: '/dashboard/contracts/$contractId/invoices'
      preLoaderRoute: typeof DashboardContractsContractIdInvoicesRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
    '/dashboard/contracts/$contractId/payroll': {
      id: '/dashboard/contracts/$contractId/payroll'
      path: '/payroll'
      fullPath: '/dashboard/contracts/$contractId/payroll'
      preLoaderRoute: typeof DashboardContractsContractIdPayrollRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
  }
}

interface DashboardContractsContractIdRouteRouteChildren {
  DashboardContractsContractIdActivityRoute: typeof DashboardContractsContractIdActivityRoute
  DashboardContractsContractIdDeadlinesRoute: typeof DashboardContractsContractIdDeadlinesRoute
  DashboardContractsContractIdDocumentsRoute: typeof DashboardContractsContractIdDocumentsRoute
  DashboardContractsContractIdEmployeesRoute: typeof DashboardContractsContractIdEmployeesRoute
  DashboardContractsContractIdInvoicesRoute: typeof DashboardContractsContractIdInvoicesRoute
  DashboardContractsContractIdPayrollRoute: typeof DashboardContractsContractIdPayrollRoute
  DashboardContractsContractIdIndexRoute: typeof DashboardContractsContractIdIndexRoute
}

const DashboardContractsContractIdRouteRouteChildren: DashboardContractsContractIdRouteRouteChildren =
  {
    DashboardContractsContractIdActivityRoute:
      DashboardContractsContractIdActivityRoute,
    DashboardContractsContractIdDeadlinesRoute:
      DashboardContractsContractIdDeadlinesRoute,
    DashboardContractsContractIdDocumentsRoute:
      DashboardContractsContractIdDocumentsRoute,
    DashboardContractsContractIdEmployeesRoute:
      DashboardContractsContractIdEmployeesRoute,
    DashboardContractsContractIdInvoicesRoute:
      DashboardContractsContractIdInvoicesRoute,
    DashboardContractsContractIdPayrollRoute:
      DashboardContractsContractIdPayrollRoute,
    DashboardContractsContractIdIndexRoute:
      DashboardContractsContractIdIndexRoute,
  }

const DashboardContractsContractIdRouteRouteWithChildren =
  DashboardContractsContractIdRouteRoute._addFileChildren(
    DashboardContractsContractIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardContractsContractIdRouteRoute: typeof DashboardContractsContractIdRouteRouteWithChildren
  DashboardContractsNewRoute: typeof DashboardContractsNewRoute
  DashboardEmployeesEmployeeIdRoute: typeof DashboardEmployeesEmployeeIdRoute
  DashboardEmployeesNewRoute: typeof DashboardEmployeesNewRoute
  DashboardInvoicesInvoiceIdRoute: typeof DashboardInvoicesInvoiceIdRoute
  DashboardInvoicesNewRoute: typeof DashboardInvoicesNewRoute
  DashboardPayrollPayrollIdRoute: typeof DashboardPayrollPayrollIdRoute
  DashboardPayrollNewRoute: typeof DashboardPayrollNewRoute
  DashboardSettingsOrganizationRoute: typeof DashboardSettingsOrganizationRoute
  DashboardSettingsTaxRoute: typeof DashboardSettingsTaxRoute
  DashboardContractsIndexRoute: typeof DashboardContractsIndexRoute
  DashboardEmployeesIndexRoute: typeof DashboardEmployeesIndexRoute
  DashboardInvoicesIndexRoute: typeof DashboardInvoicesIndexRoute
  DashboardPayrollIndexRoute: typeof DashboardPayrollIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardContractsContractIdRouteRoute:
    DashboardContractsContractIdRouteRouteWithChildren,
  DashboardContractsNewRoute: DashboardContractsNewRoute,
  DashboardEmployeesEmployeeIdRoute: DashboardEmployeesEmployeeIdRoute,
  DashboardEmployeesNewRoute: DashboardEmployeesNewRoute,
  DashboardInvoicesInvoiceIdRoute: DashboardInvoicesInvoiceIdRoute,
  DashboardInvoicesNewRoute: DashboardInvoicesNewRoute,
  DashboardPayrollPayrollIdRoute: DashboardPayrollPayrollIdRoute,
  DashboardPayrollNewRoute: DashboardPayrollNewRoute,
  DashboardSettingsOrganizationRoute: DashboardSettingsOrganizationRoute,
  DashboardSettingsTaxRoute: DashboardSettingsTaxRoute,
  DashboardContractsIndexRoute: DashboardContractsIndexRoute,
  DashboardEmployeesIndexRoute: DashboardEmployeesIndexRoute,
  DashboardInvoicesIndexRoute: DashboardInvoicesIndexRoute,
  DashboardPayrollIndexRoute: DashboardPayrollIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
