/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateOrganizationRouteImport } from './routes/create-organization'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardContractsRouteRouteImport } from './routes/dashboard/contracts/route'
import { Route as DashboardEmployeesRouteRouteImport } from './routes/dashboard/employees/route'
import { Route as DashboardInvoicesRouteRouteImport } from './routes/dashboard/invoices/route'
import { Route as DashboardPayrollRouteRouteImport } from './routes/dashboard/payroll/route'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardContractsIndexRouteImport } from './routes/dashboard/contracts/index'
import { Route as DashboardContractsContractIdRouteRouteImport } from './routes/dashboard/contracts/$contractId/route'
import { Route as DashboardContractsNewRouteImport } from './routes/dashboard/contracts/new'
import { Route as DashboardEmployeesIndexRouteImport } from './routes/dashboard/employees/index'
import { Route as DashboardEmployeesEmployeeIdRouteImport } from './routes/dashboard/employees/$employeeId'
import { Route as DashboardEmployeesNewRouteImport } from './routes/dashboard/employees/new'
import { Route as DashboardInvoicesIndexRouteImport } from './routes/dashboard/invoices/index'
import { Route as DashboardInvoicesInvoiceIdRouteImport } from './routes/dashboard/invoices/$invoiceId'
import { Route as DashboardInvoicesNewRouteImport } from './routes/dashboard/invoices/new'
import { Route as DashboardPayrollIndexRouteImport } from './routes/dashboard/payroll/index'
import { Route as DashboardPayrollPayrollIdRouteImport } from './routes/dashboard/payroll/$payrollId'
import { Route as DashboardPayrollNewRouteImport } from './routes/dashboard/payroll/new'
import { Route as DashboardSettingsOrganizationRouteRouteImport } from './routes/dashboard/settings/organization/route'
import { Route as DashboardSettingsTaxRouteRouteImport } from './routes/dashboard/settings/tax/route'
import { Route as DashboardContractsContractIdIndexRouteImport } from './routes/dashboard/contracts/$contractId/index'
import { Route as DashboardContractsContractIdActivityRouteImport } from './routes/dashboard/contracts/$contractId/activity'
import { Route as DashboardContractsContractIdDeadlinesRouteImport } from './routes/dashboard/contracts/$contractId/deadlines'
import { Route as DashboardContractsContractIdDocumentsRouteImport } from './routes/dashboard/contracts/$contractId/documents'
import { Route as DashboardContractsContractIdEmployeesRouteImport } from './routes/dashboard/contracts/$contractId/employees'
import { Route as DashboardContractsContractIdInvoicesRouteImport } from './routes/dashboard/contracts/$contractId/invoices'
import { Route as DashboardContractsContractIdPayrollRouteImport } from './routes/dashboard/contracts/$contractId/payroll'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContractsRouteRoute = DashboardContractsRouteRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmployeesRouteRoute = DashboardEmployeesRouteRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvoicesRouteRoute = DashboardInvoicesRouteRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPayrollRouteRoute = DashboardPayrollRouteRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContractsIndexRoute = DashboardContractsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardContractsRouteRoute,
} as any)
const DashboardContractsContractIdRouteRoute =
  DashboardContractsContractIdRouteRouteImport.update({
    id: '/$contractId',
    path: '/$contractId',
    getParentRoute: () => DashboardContractsRouteRoute,
  } as any)
const DashboardContractsNewRoute = DashboardContractsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardContractsRouteRoute,
} as any)
const DashboardEmployeesIndexRoute = DashboardEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardEmployeesRouteRoute,
} as any)
const DashboardEmployeesEmployeeIdRoute =
  DashboardEmployeesEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => DashboardEmployeesRouteRoute,
  } as any)
const DashboardEmployeesNewRoute = DashboardEmployeesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardEmployeesRouteRoute,
} as any)
const DashboardInvoicesIndexRoute = DashboardInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardInvoicesRouteRoute,
} as any)
const DashboardInvoicesInvoiceIdRoute =
  DashboardInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => DashboardInvoicesRouteRoute,
  } as any)
const DashboardInvoicesNewRoute = DashboardInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardInvoicesRouteRoute,
} as any)
const DashboardPayrollIndexRoute = DashboardPayrollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPayrollRouteRoute,
} as any)
const DashboardPayrollPayrollIdRoute =
  DashboardPayrollPayrollIdRouteImport.update({
    id: '/$payrollId',
    path: '/$payrollId',
    getParentRoute: () => DashboardPayrollRouteRoute,
  } as any)
const DashboardPayrollNewRoute = DashboardPayrollNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardPayrollRouteRoute,
} as any)
const DashboardSettingsOrganizationRouteRoute =
  DashboardSettingsOrganizationRouteRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsTaxRouteRoute =
  DashboardSettingsTaxRouteRouteImport.update({
    id: '/tax',
    path: '/tax',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardContractsContractIdIndexRoute =
  DashboardContractsContractIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)
const DashboardContractsContractIdActivityRoute =
  DashboardContractsContractIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)
const DashboardContractsContractIdDeadlinesRoute =
  DashboardContractsContractIdDeadlinesRouteImport.update({
    id: '/deadlines',
    path: '/deadlines',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)
const DashboardContractsContractIdDocumentsRoute =
  DashboardContractsContractIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)
const DashboardContractsContractIdEmployeesRoute =
  DashboardContractsContractIdEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)
const DashboardContractsContractIdInvoicesRoute =
  DashboardContractsContractIdInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)
const DashboardContractsContractIdPayrollRoute =
  DashboardContractsContractIdPayrollRouteImport.update({
    id: '/payroll',
    path: '/payroll',
    getParentRoute: () => DashboardContractsContractIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/create-organization': typeof CreateOrganizationRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard/contracts': typeof DashboardContractsRouteRouteWithChildren
  '/dashboard/employees': typeof DashboardEmployeesRouteRouteWithChildren
  '/dashboard/invoices': typeof DashboardInvoicesRouteRouteWithChildren
  '/dashboard/payroll': typeof DashboardPayrollRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/contracts/$contractId': typeof DashboardContractsContractIdRouteRouteWithChildren
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRouteRoute
  '/dashboard/settings/tax': typeof DashboardSettingsTaxRouteRoute
  '/dashboard/contracts/new': typeof DashboardContractsNewRoute
  '/dashboard/employees/$employeeId': typeof DashboardEmployeesEmployeeIdRoute
  '/dashboard/employees/new': typeof DashboardEmployeesNewRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/invoices/new': typeof DashboardInvoicesNewRoute
  '/dashboard/payroll/$payrollId': typeof DashboardPayrollPayrollIdRoute
  '/dashboard/payroll/new': typeof DashboardPayrollNewRoute
  '/dashboard/contracts/': typeof DashboardContractsIndexRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/dashboard/payroll/': typeof DashboardPayrollIndexRoute
  '/dashboard/contracts/$contractId/activity': typeof DashboardContractsContractIdActivityRoute
  '/dashboard/contracts/$contractId/deadlines': typeof DashboardContractsContractIdDeadlinesRoute
  '/dashboard/contracts/$contractId/documents': typeof DashboardContractsContractIdDocumentsRoute
  '/dashboard/contracts/$contractId/employees': typeof DashboardContractsContractIdEmployeesRoute
  '/dashboard/contracts/$contractId/invoices': typeof DashboardContractsContractIdInvoicesRoute
  '/dashboard/contracts/$contractId/payroll': typeof DashboardContractsContractIdPayrollRoute
  '/dashboard/contracts/$contractId/': typeof DashboardContractsContractIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRouteRoute
  '/dashboard/settings/tax': typeof DashboardSettingsTaxRouteRoute
  '/dashboard/contracts/new': typeof DashboardContractsNewRoute
  '/dashboard/employees/$employeeId': typeof DashboardEmployeesEmployeeIdRoute
  '/dashboard/employees/new': typeof DashboardEmployeesNewRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/invoices/new': typeof DashboardInvoicesNewRoute
  '/dashboard/payroll/$payrollId': typeof DashboardPayrollPayrollIdRoute
  '/dashboard/payroll/new': typeof DashboardPayrollNewRoute
  '/dashboard/contracts': typeof DashboardContractsIndexRoute
  '/dashboard/employees': typeof DashboardEmployeesIndexRoute
  '/dashboard/invoices': typeof DashboardInvoicesIndexRoute
  '/dashboard/payroll': typeof DashboardPayrollIndexRoute
  '/dashboard/contracts/$contractId/activity': typeof DashboardContractsContractIdActivityRoute
  '/dashboard/contracts/$contractId/deadlines': typeof DashboardContractsContractIdDeadlinesRoute
  '/dashboard/contracts/$contractId/documents': typeof DashboardContractsContractIdDocumentsRoute
  '/dashboard/contracts/$contractId/employees': typeof DashboardContractsContractIdEmployeesRoute
  '/dashboard/contracts/$contractId/invoices': typeof DashboardContractsContractIdInvoicesRoute
  '/dashboard/contracts/$contractId/payroll': typeof DashboardContractsContractIdPayrollRoute
  '/dashboard/contracts/$contractId': typeof DashboardContractsContractIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/create-organization': typeof CreateOrganizationRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard/contracts': typeof DashboardContractsRouteRouteWithChildren
  '/dashboard/employees': typeof DashboardEmployeesRouteRouteWithChildren
  '/dashboard/invoices': typeof DashboardInvoicesRouteRouteWithChildren
  '/dashboard/payroll': typeof DashboardPayrollRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/contracts/$contractId': typeof DashboardContractsContractIdRouteRouteWithChildren
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRouteRoute
  '/dashboard/settings/tax': typeof DashboardSettingsTaxRouteRoute
  '/dashboard/contracts/new': typeof DashboardContractsNewRoute
  '/dashboard/employees/$employeeId': typeof DashboardEmployeesEmployeeIdRoute
  '/dashboard/employees/new': typeof DashboardEmployeesNewRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/invoices/new': typeof DashboardInvoicesNewRoute
  '/dashboard/payroll/$payrollId': typeof DashboardPayrollPayrollIdRoute
  '/dashboard/payroll/new': typeof DashboardPayrollNewRoute
  '/dashboard/contracts/': typeof DashboardContractsIndexRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/dashboard/payroll/': typeof DashboardPayrollIndexRoute
  '/dashboard/contracts/$contractId/activity': typeof DashboardContractsContractIdActivityRoute
  '/dashboard/contracts/$contractId/deadlines': typeof DashboardContractsContractIdDeadlinesRoute
  '/dashboard/contracts/$contractId/documents': typeof DashboardContractsContractIdDocumentsRoute
  '/dashboard/contracts/$contractId/employees': typeof DashboardContractsContractIdEmployeesRoute
  '/dashboard/contracts/$contractId/invoices': typeof DashboardContractsContractIdInvoicesRoute
  '/dashboard/contracts/$contractId/payroll': typeof DashboardContractsContractIdPayrollRoute
  '/dashboard/contracts/$contractId/': typeof DashboardContractsContractIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/create-organization'
    | '/welcome'
    | '/dashboard/contracts'
    | '/dashboard/employees'
    | '/dashboard/invoices'
    | '/dashboard/payroll'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/contracts/$contractId'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/tax'
    | '/dashboard/contracts/new'
    | '/dashboard/employees/$employeeId'
    | '/dashboard/employees/new'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/invoices/new'
    | '/dashboard/payroll/$payrollId'
    | '/dashboard/payroll/new'
    | '/dashboard/contracts/'
    | '/dashboard/employees/'
    | '/dashboard/invoices/'
    | '/dashboard/payroll/'
    | '/dashboard/contracts/$contractId/activity'
    | '/dashboard/contracts/$contractId/deadlines'
    | '/dashboard/contracts/$contractId/documents'
    | '/dashboard/contracts/$contractId/employees'
    | '/dashboard/contracts/$contractId/invoices'
    | '/dashboard/contracts/$contractId/payroll'
    | '/dashboard/contracts/$contractId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organization'
    | '/welcome'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/tax'
    | '/dashboard/contracts/new'
    | '/dashboard/employees/$employeeId'
    | '/dashboard/employees/new'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/invoices/new'
    | '/dashboard/payroll/$payrollId'
    | '/dashboard/payroll/new'
    | '/dashboard/contracts'
    | '/dashboard/employees'
    | '/dashboard/invoices'
    | '/dashboard/payroll'
    | '/dashboard/contracts/$contractId/activity'
    | '/dashboard/contracts/$contractId/deadlines'
    | '/dashboard/contracts/$contractId/documents'
    | '/dashboard/contracts/$contractId/employees'
    | '/dashboard/contracts/$contractId/invoices'
    | '/dashboard/contracts/$contractId/payroll'
    | '/dashboard/contracts/$contractId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/create-organization'
    | '/welcome'
    | '/dashboard/contracts'
    | '/dashboard/employees'
    | '/dashboard/invoices'
    | '/dashboard/payroll'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/contracts/$contractId'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/tax'
    | '/dashboard/contracts/new'
    | '/dashboard/employees/$employeeId'
    | '/dashboard/employees/new'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/invoices/new'
    | '/dashboard/payroll/$payrollId'
    | '/dashboard/payroll/new'
    | '/dashboard/contracts/'
    | '/dashboard/employees/'
    | '/dashboard/invoices/'
    | '/dashboard/payroll/'
    | '/dashboard/contracts/$contractId/activity'
    | '/dashboard/contracts/$contractId/deadlines'
    | '/dashboard/contracts/$contractId/documents'
    | '/dashboard/contracts/$contractId/employees'
    | '/dashboard/contracts/$contractId/invoices'
    | '/dashboard/contracts/$contractId/payroll'
    | '/dashboard/contracts/$contractId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  CreateOrganizationRoute: typeof CreateOrganizationRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organization': {
      id: '/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof CreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contracts': {
      id: '/dashboard/contracts'
      path: '/contracts'
      fullPath: '/dashboard/contracts'
      preLoaderRoute: typeof DashboardContractsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/employees': {
      id: '/dashboard/employees'
      path: '/employees'
      fullPath: '/dashboard/employees'
      preLoaderRoute: typeof DashboardEmployeesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/payroll': {
      id: '/dashboard/payroll'
      path: '/payroll'
      fullPath: '/dashboard/payroll'
      preLoaderRoute: typeof DashboardPayrollRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contracts/': {
      id: '/dashboard/contracts/'
      path: '/'
      fullPath: '/dashboard/contracts/'
      preLoaderRoute: typeof DashboardContractsIndexRouteImport
      parentRoute: typeof DashboardContractsRouteRoute
    }
    '/dashboard/contracts/$contractId': {
      id: '/dashboard/contracts/$contractId'
      path: '/$contractId'
      fullPath: '/dashboard/contracts/$contractId'
      preLoaderRoute: typeof DashboardContractsContractIdRouteRouteImport
      parentRoute: typeof DashboardContractsRouteRoute
    }
    '/dashboard/contracts/new': {
      id: '/dashboard/contracts/new'
      path: '/new'
      fullPath: '/dashboard/contracts/new'
      preLoaderRoute: typeof DashboardContractsNewRouteImport
      parentRoute: typeof DashboardContractsRouteRoute
    }
    '/dashboard/employees/': {
      id: '/dashboard/employees/'
      path: '/'
      fullPath: '/dashboard/employees/'
      preLoaderRoute: typeof DashboardEmployeesIndexRouteImport
      parentRoute: typeof DashboardEmployeesRouteRoute
    }
    '/dashboard/employees/$employeeId': {
      id: '/dashboard/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/dashboard/employees/$employeeId'
      preLoaderRoute: typeof DashboardEmployeesEmployeeIdRouteImport
      parentRoute: typeof DashboardEmployeesRouteRoute
    }
    '/dashboard/employees/new': {
      id: '/dashboard/employees/new'
      path: '/new'
      fullPath: '/dashboard/employees/new'
      preLoaderRoute: typeof DashboardEmployeesNewRouteImport
      parentRoute: typeof DashboardEmployeesRouteRoute
    }
    '/dashboard/invoices/': {
      id: '/dashboard/invoices/'
      path: '/'
      fullPath: '/dashboard/invoices/'
      preLoaderRoute: typeof DashboardInvoicesIndexRouteImport
      parentRoute: typeof DashboardInvoicesRouteRoute
    }
    '/dashboard/invoices/$invoiceId': {
      id: '/dashboard/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/dashboard/invoices/$invoiceId'
      preLoaderRoute: typeof DashboardInvoicesInvoiceIdRouteImport
      parentRoute: typeof DashboardInvoicesRouteRoute
    }
    '/dashboard/invoices/new': {
      id: '/dashboard/invoices/new'
      path: '/new'
      fullPath: '/dashboard/invoices/new'
      preLoaderRoute: typeof DashboardInvoicesNewRouteImport
      parentRoute: typeof DashboardInvoicesRouteRoute
    }
    '/dashboard/payroll/': {
      id: '/dashboard/payroll/'
      path: '/'
      fullPath: '/dashboard/payroll/'
      preLoaderRoute: typeof DashboardPayrollIndexRouteImport
      parentRoute: typeof DashboardPayrollRouteRoute
    }
    '/dashboard/payroll/$payrollId': {
      id: '/dashboard/payroll/$payrollId'
      path: '/$payrollId'
      fullPath: '/dashboard/payroll/$payrollId'
      preLoaderRoute: typeof DashboardPayrollPayrollIdRouteImport
      parentRoute: typeof DashboardPayrollRouteRoute
    }
    '/dashboard/payroll/new': {
      id: '/dashboard/payroll/new'
      path: '/new'
      fullPath: '/dashboard/payroll/new'
      preLoaderRoute: typeof DashboardPayrollNewRouteImport
      parentRoute: typeof DashboardPayrollRouteRoute
    }
    '/dashboard/settings/organization': {
      id: '/dashboard/settings/organization'
      path: '/organization'
      fullPath: '/dashboard/settings/organization'
      preLoaderRoute: typeof DashboardSettingsOrganizationRouteRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/tax': {
      id: '/dashboard/settings/tax'
      path: '/tax'
      fullPath: '/dashboard/settings/tax'
      preLoaderRoute: typeof DashboardSettingsTaxRouteRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/contracts/$contractId/': {
      id: '/dashboard/contracts/$contractId/'
      path: '/'
      fullPath: '/dashboard/contracts/$contractId/'
      preLoaderRoute: typeof DashboardContractsContractIdIndexRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
    '/dashboard/contracts/$contractId/activity': {
      id: '/dashboard/contracts/$contractId/activity'
      path: '/activity'
      fullPath: '/dashboard/contracts/$contractId/activity'
      preLoaderRoute: typeof DashboardContractsContractIdActivityRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
    '/dashboard/contracts/$contractId/deadlines': {
      id: '/dashboard/contracts/$contractId/deadlines'
      path: '/deadlines'
      fullPath: '/dashboard/contracts/$contractId/deadlines'
      preLoaderRoute: typeof DashboardContractsContractIdDeadlinesRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
    '/dashboard/contracts/$contractId/documents': {
      id: '/dashboard/contracts/$contractId/documents'
      path: '/documents'
      fullPath: '/dashboard/contracts/$contractId/documents'
      preLoaderRoute: typeof DashboardContractsContractIdDocumentsRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
    '/dashboard/contracts/$contractId/employees': {
      id: '/dashboard/contracts/$contractId/employees'
      path: '/employees'
      fullPath: '/dashboard/contracts/$contractId/employees'
      preLoaderRoute: typeof DashboardContractsContractIdEmployeesRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
    '/dashboard/contracts/$contractId/invoices': {
      id: '/dashboard/contracts/$contractId/invoices'
      path: '/invoices'
      fullPath: '/dashboard/contracts/$contractId/invoices'
      preLoaderRoute: typeof DashboardContractsContractIdInvoicesRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
    '/dashboard/contracts/$contractId/payroll': {
      id: '/dashboard/contracts/$contractId/payroll'
      path: '/payroll'
      fullPath: '/dashboard/contracts/$contractId/payroll'
      preLoaderRoute: typeof DashboardContractsContractIdPayrollRouteImport
      parentRoute: typeof DashboardContractsContractIdRouteRoute
    }
  }
}

interface DashboardContractsContractIdRouteRouteChildren {
  DashboardContractsContractIdActivityRoute: typeof DashboardContractsContractIdActivityRoute
  DashboardContractsContractIdDeadlinesRoute: typeof DashboardContractsContractIdDeadlinesRoute
  DashboardContractsContractIdDocumentsRoute: typeof DashboardContractsContractIdDocumentsRoute
  DashboardContractsContractIdEmployeesRoute: typeof DashboardContractsContractIdEmployeesRoute
  DashboardContractsContractIdInvoicesRoute: typeof DashboardContractsContractIdInvoicesRoute
  DashboardContractsContractIdPayrollRoute: typeof DashboardContractsContractIdPayrollRoute
  DashboardContractsContractIdIndexRoute: typeof DashboardContractsContractIdIndexRoute
}

const DashboardContractsContractIdRouteRouteChildren: DashboardContractsContractIdRouteRouteChildren =
  {
    DashboardContractsContractIdActivityRoute:
      DashboardContractsContractIdActivityRoute,
    DashboardContractsContractIdDeadlinesRoute:
      DashboardContractsContractIdDeadlinesRoute,
    DashboardContractsContractIdDocumentsRoute:
      DashboardContractsContractIdDocumentsRoute,
    DashboardContractsContractIdEmployeesRoute:
      DashboardContractsContractIdEmployeesRoute,
    DashboardContractsContractIdInvoicesRoute:
      DashboardContractsContractIdInvoicesRoute,
    DashboardContractsContractIdPayrollRoute:
      DashboardContractsContractIdPayrollRoute,
    DashboardContractsContractIdIndexRoute:
      DashboardContractsContractIdIndexRoute,
  }

const DashboardContractsContractIdRouteRouteWithChildren =
  DashboardContractsContractIdRouteRoute._addFileChildren(
    DashboardContractsContractIdRouteRouteChildren,
  )

interface DashboardContractsRouteRouteChildren {
  DashboardContractsContractIdRouteRoute: typeof DashboardContractsContractIdRouteRouteWithChildren
  DashboardContractsNewRoute: typeof DashboardContractsNewRoute
  DashboardContractsIndexRoute: typeof DashboardContractsIndexRoute
}

const DashboardContractsRouteRouteChildren: DashboardContractsRouteRouteChildren =
  {
    DashboardContractsContractIdRouteRoute:
      DashboardContractsContractIdRouteRouteWithChildren,
    DashboardContractsNewRoute: DashboardContractsNewRoute,
    DashboardContractsIndexRoute: DashboardContractsIndexRoute,
  }

const DashboardContractsRouteRouteWithChildren =
  DashboardContractsRouteRoute._addFileChildren(
    DashboardContractsRouteRouteChildren,
  )

interface DashboardEmployeesRouteRouteChildren {
  DashboardEmployeesEmployeeIdRoute: typeof DashboardEmployeesEmployeeIdRoute
  DashboardEmployeesNewRoute: typeof DashboardEmployeesNewRoute
  DashboardEmployeesIndexRoute: typeof DashboardEmployeesIndexRoute
}

const DashboardEmployeesRouteRouteChildren: DashboardEmployeesRouteRouteChildren =
  {
    DashboardEmployeesEmployeeIdRoute: DashboardEmployeesEmployeeIdRoute,
    DashboardEmployeesNewRoute: DashboardEmployeesNewRoute,
    DashboardEmployeesIndexRoute: DashboardEmployeesIndexRoute,
  }

const DashboardEmployeesRouteRouteWithChildren =
  DashboardEmployeesRouteRoute._addFileChildren(
    DashboardEmployeesRouteRouteChildren,
  )

interface DashboardInvoicesRouteRouteChildren {
  DashboardInvoicesInvoiceIdRoute: typeof DashboardInvoicesInvoiceIdRoute
  DashboardInvoicesNewRoute: typeof DashboardInvoicesNewRoute
  DashboardInvoicesIndexRoute: typeof DashboardInvoicesIndexRoute
}

const DashboardInvoicesRouteRouteChildren: DashboardInvoicesRouteRouteChildren =
  {
    DashboardInvoicesInvoiceIdRoute: DashboardInvoicesInvoiceIdRoute,
    DashboardInvoicesNewRoute: DashboardInvoicesNewRoute,
    DashboardInvoicesIndexRoute: DashboardInvoicesIndexRoute,
  }

const DashboardInvoicesRouteRouteWithChildren =
  DashboardInvoicesRouteRoute._addFileChildren(
    DashboardInvoicesRouteRouteChildren,
  )

interface DashboardPayrollRouteRouteChildren {
  DashboardPayrollPayrollIdRoute: typeof DashboardPayrollPayrollIdRoute
  DashboardPayrollNewRoute: typeof DashboardPayrollNewRoute
  DashboardPayrollIndexRoute: typeof DashboardPayrollIndexRoute
}

const DashboardPayrollRouteRouteChildren: DashboardPayrollRouteRouteChildren = {
  DashboardPayrollPayrollIdRoute: DashboardPayrollPayrollIdRoute,
  DashboardPayrollNewRoute: DashboardPayrollNewRoute,
  DashboardPayrollIndexRoute: DashboardPayrollIndexRoute,
}

const DashboardPayrollRouteRouteWithChildren =
  DashboardPayrollRouteRoute._addFileChildren(
    DashboardPayrollRouteRouteChildren,
  )

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsOrganizationRouteRoute: typeof DashboardSettingsOrganizationRouteRoute
  DashboardSettingsTaxRouteRoute: typeof DashboardSettingsTaxRouteRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsOrganizationRouteRoute:
      DashboardSettingsOrganizationRouteRoute,
    DashboardSettingsTaxRouteRoute: DashboardSettingsTaxRouteRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardContractsRouteRoute: typeof DashboardContractsRouteRouteWithChildren
  DashboardEmployeesRouteRoute: typeof DashboardEmployeesRouteRouteWithChildren
  DashboardInvoicesRouteRoute: typeof DashboardInvoicesRouteRouteWithChildren
  DashboardPayrollRouteRoute: typeof DashboardPayrollRouteRouteWithChildren
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardContractsRouteRoute: DashboardContractsRouteRouteWithChildren,
  DashboardEmployeesRouteRoute: DashboardEmployeesRouteRouteWithChildren,
  DashboardInvoicesRouteRoute: DashboardInvoicesRouteRouteWithChildren,
  DashboardPayrollRouteRoute: DashboardPayrollRouteRouteWithChildren,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  CreateOrganizationRoute: CreateOrganizationRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
